/**
 * packages/db/src/index.ts
 *
 * Exports a singleton PrismaClient instance.
 *
 * The global pattern prevents multiple Prisma Client instances from being
 * created during Next.js hot-module replacement in development. Without this,
 * each HMR cycle would instantiate a new client and exhaust the PostgreSQL
 * connection pool.
 *
 * Reference: https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices
 */

import { PrismaClient } from '@prisma/client';

// Extend the NodeJS global type to hold our cached Prisma instance
declare global {
  // eslint-disable-next-line no-var
  var __prisma: PrismaClient | undefined;
}

function createPrismaClient(): PrismaClient {
  return new PrismaClient({
    log:
      process.env.NODE_ENV === 'development'
        ? ['query', 'error', 'warn']
        : ['error'],
  });
}

// In production, always create a fresh client.
// In development, reuse the global instance across HMR reloads.
export const prisma: PrismaClient =
  process.env.NODE_ENV === 'production'
    ? createPrismaClient()
    : (globalThis.__prisma ??= createPrismaClient());

// Re-export all types generated by Prisma so consumers can do:
//   import { prisma, type Account, type Prisma } from '@noram/db';
export {
  Prisma,
  type Account,
  type User,
  type Opportunity,
  type FinancialActual,
  type Target,
  type VampRecord,
  TargetType,
} from '@prisma/client';

export default prisma;
